name: graphql-client-example
version: 0.1.0

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

dependencies:
- aeson
- base
- graphql-client
- text

library:
  source-dirs: src

executable:
  source-dirs:    exe
  main:           Main.hs
  dependencies:
    - graphql-client-example

tests:
  graphql-example-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson-qq
      - bytestring
      - graphql-client-example
      - tasty
      - tasty-golden
