name: graphql-client-example
version: 0.1.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances

dependencies:
- aeson
- base
- graphql-client
- text

library:
  source-dirs: src

executable:
  source-dirs:    exe
  main:           Main.hs
  dependencies:
    - graphql-client-example

tests:
  graphql-example-test:
    source-dirs:  test
    main:         Main.hs
    dependencies:
      - aeson-qq >= 0.8.4
      - bytestring
      - graphql-client-example
      - tasty
      - tasty-golden
