version: 2.1

aliases:
  - &param_stack_yaml
    stack_yaml:
      type: string
      default: stack.yaml
  - &param_latest
    latest:
      type: boolean
      default: false

  - &stack_cache_key
    v0-{{ checksum "stack-cache-key.txt" }}

  - &yarn_cache_key
    v0-{{ checksum "yarn-cache-key.txt" }}

executors:
  centos7:
    parameters:
      <<: [*param_stack_yaml, *param_latest]

    docker:
      - image: centos:7
    working_directory: /root/src
    shell: /bin/bash -eux -o pipefail
    environment:
      STACK_YAML: << parameters.stack_yaml >>
      CI_LATEST: <<# parameters.latest >>1<</ parameters.latest >>
      LANG: en_US.UTF-8

jobs:
  run_build_and_test:
    parameters:
      <<: [*param_stack_yaml, *param_latest]

    executor:
      name: centos7
      stack_yaml: << parameters.stack_yaml >>
      latest: << parameters.latest >>

    steps:
      # init
      - checkout
      - run:
          name: Build cache keys
          command: |
            STACK_FILES=(
              "${STACK_YAML}"
              graphql-client/package.yaml
              example/package.yaml
            )
            cat "${STACK_FILES[@]}" > stack-cache-key.txt
            curl -sSL https://get.haskellstack.org/ | sed -n 's/^STACK_VERSION="\(.*\)"/\1/p' >> stack-cache-key.txt

            YARN_FILES=(
              yarn.lock
            )
            cat "${YARN_FILES[@]}" > yarn-cache-key.txt

      # install stack and dependencies
      - run:
          name: Install stack
          command: |
            curl -sSL https://get.haskellstack.org/ | sh
            stack --version
      - run:
          name: Install system dependencies
          command: yum install -y zlib-devel
      - restore_cache:
          key: *stack_cache_key
      - run:
          name: Build external dependencies
          command: |
            STACK_ARGS=(--test --only-dependencies)
            if [[ -n "${CI_LATEST}" ]]; then
                STACK_ARGS+=(--haddock)
            fi

            stack build "${STACK_ARGS[@]}"

            # build hlint/stylish-haskell for cache
            if [[ -n "${CI_LATEST}" ]]; then
                stack build hlint stylish-haskell
            fi
      - save_cache:
          key: *stack_cache_key
          paths:
            - ~/.stack
            - .stack-work

      # install yarn and dependencies
      - run:
          name: Install yarn
          command: |
            curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
            curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -
            yum install -y yarn
      - restore_cache:
          key: *yarn_cache_key
      - run:
          name: Install yarn dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          key: *yarn_cache_key
          paths:
            - node_modules

      # lint, build, and test
      - when:
          condition: << parameters.latest >>
          steps:
            - run:
                name: Lint
                command: |
                  set +e
                  STATUS=0
                  scripts/eslint.sh || STATUS=1
                  scripts/hlint.sh || STATUS=1
                  scripts/stylish-haskell.sh || STATUS=1
                  exit "${STATUS}"
      - run:
          name: Build
          command: |
            STACK_ARGS=(
                --test
                --no-run-tests
            )
            if [[ -n "${CI_LATEST}" ]]; then
                STACK_ARGS+=(--haddock)
            fi

            stack build "${STACK_ARGS[@]}" --ghc-options -Werror graphql-client

            # don't error on warnings in the example, because we want the source code to
            # be clean and easy to read
            stack build "${STACK_ARGS[@]}" graphql-client-example

            if [[ -n "${CI_LATEST}" ]]; then
              mkdir -p .ci/
              tar czf .ci/haddock-docs.tar.gz -C "$(find graphql-client/.stack-work/dist -regex '.*/doc/html/[^/]*')" .
            fi
      - when:
          condition: << parameters.latest >>
          steps:
            - store_artifacts:
                path: .ci/
      - run:
          name: Ensure that example API is up to date
          command: |
            yarn graphql build
            yarn example codegen
            git --no-pager diff --exit-code example/src/Example/GraphQL/API.hs
      - run:
          name: Test
          command: stack test

      - run:
          name: Run example
          command: stack exec graphql-client-example

workflows:
  version: 2

  build_and_test:
    jobs:
      - run_build_and_test:
          name: test_latest
          latest: true
      - run_build_and_test:
          name: test_ghc_8.8
          stack_yaml: stack-ghc-8.8.yaml
      - run_build_and_test:
          name: test_ghc_8.6
          stack_yaml: stack-ghc-8.6.yaml
      - run_build_and_test:
          name: test_ghc_8.4
          stack_yaml: stack-ghc-8.4.yaml
      - run_build_and_test:
          name: test_ghc_8.2
          stack_yaml: stack-ghc-8.2.yaml
