name: graphql-client
version: 1.2.2
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE.md
author:
  - Brandon Chinn <brandonchinn178@gmail.com>
maintainer:
  - Brandon Chinn <brandonchinn178@gmail.com>
category: Graphql
synopsis: A client for Haskell programs to query a GraphQL API
description: A client for Haskell programs to query a GraphQL API.
extra-source-files:
  - README.md
  - CHANGELOG.md
  # Make sure graphql-codegen-haskell.js is listed in the Cabal file,
  # in the off-chance it's not built yet
  - ./js/graphql-codegen-haskell.js
  - ./js/**/*

github: brandonchinn178/graphql-client

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wunused-packages

library:
  source-dirs: src
  dependencies:
    - aeson < 3
    - aeson-schemas < 1.5
    - base < 5
    - http-client < 0.8
    - http-client-tls < 0.4
    - http-types < 0.13
    - mtl < 2.4
    - template-haskell < 3
    - text < 2.2
    - transformers < 0.7
    - unliftio-core < 0.3

executables:
  graphql-codegen:
    main: exe/Codegen.hs
    dependencies:
      - base < 5
      - bytestring < 0.12
      - file-embed < 0.1
      - optparse-applicative < 0.19
      - path < 0.10
      - path-io < 2
      - template-haskell < 3
      - typed-process < 0.3

tests:
  graphql-client-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - aeson
      - aeson-schemas
      - base
      - graphql-client
      - mtl
      - tasty
      - tasty-hunit
