name: graphql-client
version: 1.0.0
verbatim:
  cabal-version: '>= 1.10'
license: BSD3
license-file: LICENSE
author:
  - Brandon Chinn <brandon@leapyear.io>
maintainer:
  - Brandon Chinn <brandon@leapyear.io>
category: Graphql
synopsis: A client for Haskell programs to query a GraphQL API
description: A client for Haskell programs to query a GraphQL API.
extra-source-files:
  - README.md
  - CHANGELOG.md
  # Make sure graphql-codegen-haskell.js is listed in the Cabal file,
  # in the off case it's not built yet
  - ./js/graphql-codegen-haskell.js
  - ./js/**/*

github: LeapYear/graphql-client

ghc-options: -Wall
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wnoncanonical-monad-instances
  - condition: impl(ghc < 8.8)
    ghc-options:
      - -Wnoncanonical-monadfail-instances

dependencies:
- aeson >= 1.2.4.0 && < 1.6
- aeson-schemas >= 1.2 && < 1.3
- base >= 4.9 && < 5
- http-client >= 0.5.13.1 && < 0.8
- http-client-tls >= 0.3.5.3 && < 0.4
- http-types >= 0.12.1 && < 0.13
- mtl >= 2.2.2 && < 2.3
- template-haskell >= 2.12.0.0 && < 3
- text >= 1.2.3.0 && < 1.3
- transformers >= 0.5.2.0 && < 0.6
- unliftio-core >= 0.1.1.0 && < 0.3

library:
  source-dirs: src

executables:
  graphql-codegen:
    main: exe/Codegen.hs
    dependencies:
      - bytestring >= 0.10.8.2 && < 0.11
      - file-embed >= 0.0.10.1 && < 0.0.14
      - graphql-client
      - optparse-applicative >= 0.14.2.0 && < 0.15.2
      - path >= 0.6.1 && < 0.8.0
      - path-io >= 1.3.3 && < 1.7.0
      - typed-process >= 0.2.3.0 && < 0.2.7

tests:
  graphql-client-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - graphql-client
      - tasty
      - tasty-hunit
